# This is a sample configuration file
elements:
  myservice1:
    urls:
      - "https://myservice1.example.com"
  myservice2:
    urls:
      - "https://myservice2.example.com"
  myservice3:
    urls:
      - "https://myservice3.example.com"
